const PROVINCE_CODES = {
  '02': 'Albacete',
  '16': 'Cuenca',
  '36': 'Pontevedra',
  '03': 'Alicante/Alacant',
  '20': 'Gipuzkoa',
  '26': 'Rioja, La',
  '04': 'Almería',
  '17': 'Girona',
  '37': 'Salamanca',
  '01': 'Araba/Álava',
  '18': 'Granada',
  '38': 'Santa Cruz de Tenerife',
  '33': 'Asturias',
  '19': 'Guadalajara',
  '40': 'Segovia',
  '05': 'Ávila',
  '21': 'Huelva',
  '41': 'Sevilla',
  '06': 'Badajoz',
  '22': 'Huesca',
  '42': 'Soria',
  '07': 'Balears, Illes',
  '23': 'Jaén',
  '43': 'Tarragona',
  '08': 'Barcelona',
  '24': 'León',
  '44': 'Teruel',
  '48': 'Bizkaia',
  '25': 'Lleida',
  '45': 'Toledo',
  '09': 'Burgos',
  '27': 'Lugo',
  '46': 'Valencia/València',
  '10': 'Cáceres',
  '28': 'Madrid',
  '47': 'Valladolid',
  '11': 'Cádiz',
  '29': 'Málaga',
  '49': 'Zamora',
  '39': 'Cantabria',
  '30': 'Murcia',
  '50': 'Zaragoza',
  '12': 'Castellón/Castelló',
  '31': 'Navarra',
  '51': 'Ceuta',
  '13': 'Ciudad Real',
  '32': 'Ourense',
  '52': 'Melilla',
  '14': 'Córdoba',
  '34': 'Palencia',
  '15': 'Coruña, A',
  '35': 'Palmas, Las',
  '53': 'Otros territorios',
  '66': 'Extranjero'
};

export const isValidSsn = (s: string): boolean => {
  console.log(PROVINCE_CODES);
  return true;
};
